package jamfile

import (
	"bytes"
	"fmt"
	"jam/lib/jamrc"
	"strconv"
	"time"

	"mvdan.cc/sh/v3/syntax"
)

func ToSyntaxFile(document *Document) *syntax.File {
	f := &syntax.File{
		Name:  ".jamrc",
		Stmts: []*syntax.Stmt{},
	}

	f.Stmts = append(f.Stmts, &syntax.Stmt{
		Comments: []syntax.Comment{
			{Text: "!/usr/bin/env bash"},
			{Text: " jam: alias manager"},
			{Text: " This file was generated by jam."},
			{Text: " Edit at your own risk - manual edits may be overwritten."},
			{Text: " Use `jam add`, `jam enable`, `jam disable`, etc. to modify aliases."},
		},
	})

	for _, a := range document.Aliases {
		if a.AddedAt.IsZero() {
			a.AddedAt = time.Now().UTC()
		}

		declareStmt := buildMetaStmt(a)
		aliasStmt := buildAliasStmt(a)

		f.Stmts = append(f.Stmts, declareStmt, aliasStmt)
	}

	return f
}

// Write handles writing a jamfile.Document back to disk or STDOUT
func Write(document *Document, pretend bool) error {
	buffer := &bytes.Buffer{}
	render := ToSyntaxFile(document)
	if err := jamrc.Render(render, buffer); err != nil {
		return err
	}

	if pretend {
		fmt.Print(buffer.String())
		return nil
	}

	if err := jamrc.Write(buffer); err != nil {
		return err
	}

	return nil
}

func buildMetaStmt(alias Alias) *syntax.Stmt {
	arrayElems := []*syntax.ArrayElem{
		arrayKV(keyTarget, alias.Target),
		arrayKV(keyEnabled, strconv.FormatBool(alias.Enabled)),
	}
	if alias.Description != "" {
		arrayElems = append(arrayElems, arrayKV(keyDescription, alias.Description))
	}
	if !alias.AddedAt.IsZero() {
		arrayElems = append(arrayElems, arrayKV(keyAddedAt, alias.AddedAt.UTC().Format(timeLayout)))
	}

	return &syntax.Stmt{
		Cmd: &syntax.DeclClause{
			Variant: &syntax.Lit{Value: "declare"},
			Args: []*syntax.Assign{
				{
					Value: &syntax.Word{
						Parts: []syntax.WordPart{
							&syntax.Lit{Value: "-A"},
						},
					},
				},
				{
					Name:  &syntax.Lit{Value: metaPrefix + alias.Name},
					Array: &syntax.ArrayExpr{Elems: arrayElems},
				},
			},
		},
	}
}

// TODO:
//  1. syntax.Assign does not seem to be supported as a WordPart:
//     https://github.com/mvdan/sh/issues/858
//  2. This does not support converting $HOME back to tilde (~).
func buildAliasStmt(alias Alias) *syntax.Stmt {
	if !alias.Enabled {
		return &syntax.Stmt{
			Comments: []syntax.Comment{
				{Text: fmt.Sprintf(" alias %s=\"%s\"", alias.Name, alias.Target)},
			},
		}
	}

	return &syntax.Stmt{
		Cmd: &syntax.CallExpr{
			Args: []*syntax.Word{
				{
					Parts: []syntax.WordPart{
						&syntax.Lit{Value: "alias"},
					},
				},
				{
					Parts: []syntax.WordPart{
						&syntax.Lit{Value: fmt.Sprintf("%v=", alias.Name)},
						&syntax.DblQuoted{
							Parts: []syntax.WordPart{
								&syntax.Lit{Value: alias.Target},
							},
						},
					},
				},
			},
		},
	}
}

func arrayKV(key, value string) *syntax.ArrayElem {
	return &syntax.ArrayElem{
		Index: &syntax.Word{
			Parts: []syntax.WordPart{
				&syntax.Lit{Value: key},
			},
		},
		Value: &syntax.Word{
			Parts: []syntax.WordPart{
				&syntax.DblQuoted{
					Parts: []syntax.WordPart{
						&syntax.Lit{Value: value},
					},
				},
			},
		},
	}
}
