package jamrc

import "mvdan.cc/sh/v3/syntax"

// Empty returns a minimal .jamrc file AST.
func Empty() syntax.File {
	return syntax.File{
		Name: ".jamrc",
		Stmts: []*syntax.Stmt{
			{
				Comments: []syntax.Comment{
					{Text: "!/usr/bin/env bash"},
					{Text: " jam: alias manager"},
					{Text: " This file was generated by jam."},
					{Text: " Edit at your own risk - manual edits may be overwritten."},
					{Text: " Use `jam add`, `jam enable`, `jam disable`, etc. to modify aliases."},
				},
			},
		},
	}
}
